version: '3.11.4'

services:
  web:
    image: pouryach/human_resource_managment-web
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
