version: '3.8'

services:

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: hr_db
      POSTGRES_USER: pouria
      POSTGRES_PASSWORD: 19128228
    ports:
      - "5433:5432"


  web:
    image: pourya_michael/human_resource_managment-web
    build: .
    command: ["./entrypoint.sh"]
    volumes:
      - .:/code
    ports:
      - "8080:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://pouria:19128228@db/hr_db