# Generated by Django 5.1.1 on 2024-09-11 06:39

import personnel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_personnel', models.CharField(blank=True, default=personnel.models.Personnel.create_new_number_of_personnel, editable=False, max_length=100, unique=True)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('degree', models.CharField(max_length=100)),
                ('field_of_study', models.CharField(max_length=100)),
                ('career_records', models.TextField()),
                ('position', models.CharField(max_length=100)),
                ('level_for_position', models.CharField(max_length=100)),
                ('date_of_employment', models.DateField()),
            ],
        ),
    ]
