# Generated by Django 5.1.1 on 2024-09-14 11:31

import personnel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='id',
        ),
        migrations.AlterField(
            model_name='personnel',
            name='number_of_personnel',
            field=models.CharField(blank=True, default=personnel.models.Personnel.create_new_number_of_personnel, editable=False, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
