# Generated by Django 5.1.1 on 2024-09-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecruimentConditionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recruiment_condition', models.CharField(choices=[('accepted', 'Accepted'), ('reject', 'Reject'), ('uncertain', 'Uncertain')], default='No Any Data', max_length=15)),
                ('recruiment_position', models.CharField(choices=[('Software engineer', 'software engineer'), ('Front end', 'front end'), ('Full stack', 'full stack'), ('App developer', 'app developer'), ('Web developer', 'web developer')], default='No Any Data', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RecruitmentDateDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recruitment_date', models.DateField()),
                ('numberـofـdaysـreceived', models.DurationField()),
                ('numberـofـdaysـchecked', models.DurationField()),
                ('numberـofـdays_confirmed', models.DurationField()),
                ('numberـofـdays_interviews', models.DurationField()),
                ('time_spent_interview', models.DurationField()),
            ],
        ),
    ]
