# Generated by Django 5.1.1 on 2024-09-11 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruitment',
            old_name='time_spent_every_interview',
            new_name='duration_every_interview',
        ),
    ]
