# Generated by Django 5.1.1 on 2024-09-09 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recruiment_condition', models.CharField(choices=[('accepted', 'Accepted'), ('reject', 'Reject'), ('uncertain', 'Uncertain')], default='uncertain', max_length=15)),
                ('recruiment_position', models.CharField(choices=[('Software engineer', 'software engineer'), ('Front end', 'front end'), ('Full stack', 'full stack'), ('App developer', 'app developer'), ('Web developer', 'web developer'), ('No information', 'no information')], default='No information', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RecDate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recruitment_date', models.DateField()),
                ('daysـreceived', models.DurationField()),
                ('daysـchecked', models.DurationField()),
                ('days_confirmed', models.DurationField()),
                ('days_interviews', models.DurationField()),
                ('time_spent_interview', models.DurationField()),
                ('recruitment_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='date_detail', to='recruitment.reccondition')),
            ],
        ),
        migrations.DeleteModel(
            name='RecruimentConditionDetails',
        ),
        migrations.DeleteModel(
            name='RecruitmentDateDetails',
        ),
    ]
