# Generated by Django 5.1.1 on 2024-09-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_rename_time_spent_every_interview_recruitment_duration_every_interview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitment',
            name='recruitment_possition',
            field=models.CharField(choices=[('Nothing', 'nothing'), ('Front End Developer', 'front end developer'), ('Back End Developer', 'back end developer'), ('Full Stack Developer', 'full stack developer'), ('DevOps Engineer', 'devops engineer'), ('UX/UI Designer', 'ux/ui designer'), ('Network Engineer', 'network engineer')], default='Nothing', max_length=50),
        ),
    ]
