# Generated by Django 5.1.1 on 2024-09-09 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_reccondition_recdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recdate',
            name='recruitment_details',
        ),
        migrations.AddField(
            model_name='recdate',
            name='rec_condition',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rec_date', to='recruitment.reccondition'),
            preserve_default=False,
        ),
    ]
