# Generated by Django 5.1.1 on 2024-09-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_alter_recruitment_recruitment_possition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitment',
            name='recruitment_condition',
            field=models.CharField(default='Uncertain', max_length=50),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='recruitment_possition',
            field=models.CharField(default='Nothing', max_length=50),
        ),
    ]
