# Generated by Django 5.1.1 on 2024-09-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personnal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_personnal', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('degree', models.CharField(max_length=100)),
                ('fieldـofـstudy', models.CharField(max_length=100)),
                ('Careerـrecords', models.TextField()),
                ('position', models.CharField(max_length=100)),
                ('level_fo_position', models.CharField(max_length=100)),
                ('Date_of_employment', models.DateField()),
            ],
        ),
    ]
