# Generated by Django 5.1.1 on 2024-09-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnal',
            name='number_of_personnal',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
