# Generated by Django 5.1.1 on 2024-09-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(editable=False, max_length=20)),
                ('dateـofـallocation', models.DateField()),
                ('asset_code', models.CharField(max_length=10)),
            ],
        ),
    ]
