# Generated by Django 5.1.1 on 2024-09-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resources',
            name='asset_code',
        ),
        migrations.AddField(
            model_name='resources',
            name='resource_sort',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
