# Generated by Django 5.1.1 on 2024-09-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_remove_resources_asset_code_resources_resource_sort'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resources',
            name='id',
        ),
        migrations.AddField(
            model_name='resources',
            name='asset_code',
            field=models.CharField(default=1, editable=False, max_length=8, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resources',
            name='resource_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='resources',
            name='resource_sort',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
